version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:022085345551:task-definition/all-code-suite:1"
        LoadBalancerInfo:
          ContainerName: "nginx"
          ContainerPort: 80
